### ISSUE TITLE
Crash at launch 

### ISSUE THREAD

**Issue by jay213333** [Skilles/MobMincer#5]
Using 1.20.1 (Forge). I also have installed all required dependencies (Architectury API & Kotlin). Please help. 

[crash-2024-01-15_13.11.51-client.pdf](https://github.com/Skilles/MobMincer/files/13942753/crash-2024-01-15_13.11.51-client.pdf)

**Comment by Skilles** [comment]
From the logs, looks like an issue with iris and/or oculus.

I found this which might help https://github.com/Asek3/Oculus/issues/395

Feel free to reopen if the steps there don't work and removing mob mincer fixes the issue

**Comment by jay213333** [comment]
Thanks for the suggestion. However, I couldn't find a fix with the method they used. It works fine if I remove mob mincer. Darn it

**Comment by Skilles** [comment]
> Thanks for the suggestion. However, I couldn't find a fix with the method they used. It works fine if I remove mob mincer. Darn it

In that case I can take a look at what's going on. Do you have a full mod list? (You can just send the latest.log)

I've also tested previously on 1.20.2 Fabric with iris with no issues

**Comment by jay213333** [comment]
Interesting. Yes, thanks I'll attach it below. It's 205 mods - been very diligent on how each mod behaves with each other, and don't think I'm missing any dependencies. I wonder if "Sinytra Connector" (Connector) may be conflicting. 

[latest.log](https://github.com/Skilles/MobMincer/files/13943665/latest.log)

**Comment by Skilles** [comment]
I think the issue is this:
`[15Jan2024 14:54:56.085] [main/ERROR] [net.minecraftforge.fml.loading.LanguageLoadingProvider/LOADING]: Missing language kotlinforforge version [4.7,) wanted by mobmincer-1.0.2-1.20.2.jar, found 4.3.0`

See if upgrading Kotlin for Forge fixes the issue. If not you can try relaxing the requirement in the jar file.

**Comment by jay213333** [comment]
Got it thanks, so I updated that but now received the following new requests:

[15Jan2024 17:24:08.580] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'minecraft', Requested by: 'mobmincer', Expected range: '[1.20.2,)', Actual version: '1.20.1'
	Mod ID: 'neoforge', Requested by: 'mobmincer', Expected range: '[20.2,)', Actual version: '[MISSING]'

[latest.log](https://github.com/Skilles/MobMincer/files/13944059/latest.log)

**Comment by jay213333** [comment]
I'm afraid I can't update to 1.20.2 at the moment due to other projects and mods I need working only on 1.20.1

**Comment by Skilles** [comment]
Ah yeah sorry only 1.20.2 NeoForged is supported right now. Sadly 1.20.2 changed a lot in NeoForged and is no longer compatible with Forge, so it will take me some time to backport

#6

**Comment by jay213333** [comment]
Wow that's new. I bookmarked your mod and will keep an eye out for backport. Thanks again for your help

**Comment by jay213333** [comment]
Sorry, I forgot to ask if you have a Fabric-only version of Mob Mincer in 1.20.2.

**Comment by Skilles** [comment]
> Sorry, I forgot to ask if you have a Fabric-only version of Mob Mincer in 1.20.2.

The mod should work with fabric using the same jar. If you're trying to use it with Sinytra (if its updated for 1.20.2) you probably need to delete the META-INF folder from inside the jar so that it doesn't try to load it as a forge mod
